from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean
from database import Base


# A person using the app. For now they just type a name (no password).
class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(100), unique=True)
    created_at = Column(DateTime, default=datetime.utcnow)


# A lesson generated by the AI for a given topic.
class Lesson(Base):
    __tablename__ = "lessons"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer)
    topic = Column(String(200))
    lesson_text = Column(Text)
    exercise = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)


# An answer the user submitted for a lesson's exercise.
class Submission(Base):
    __tablename__ = "submissions"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer)
    lesson_id = Column(Integer)
    topic = Column(String(200))
    user_code = Column(Text)
    feedback = Column(Text)
    passed = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)